# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5testDB

development:
  <<: *default
  database: testDB


test:
  <<: *default
  database: testDB

production:
  <<: *default
  database: testDB
